### ISSUE TITLE
MacOS Error with Catalina: Etcher can't read image file, throws error.

### ISSUE THREAD

**Issue by LazyHRanch** [balena-io/etcher#2933]
Recently upgraded to macOS Catalina and found Etcher not working. I get an error: 
"Something Went wrong. If it is a compressed image, please check that the archive is not corrupted."

I know it's not the image because I'm using the same images that I used in the previous MacOS version and I verified it on a PC that the image is OK. I also tried a couple of different images to make sure it wasn't related to a specific image.

I noticed that I had to "Open" Etcher twice after installing to get through the warnings but then it opened up just fine. Amy suggestions or is anyone else seeing this error?

**Comment by lurch** [comment]
Duplicate of #2833 ?

**Comment by LazyHRanch** [comment]
It looks like that issue is with opening Etcher directly. I can get Etcher to run but when I try to write to the SD card is when I'm getting the above error. And yes it does ask for permissions when starting the burn process.
![Etcher](https://user-images.githubusercontent.com/56555265/66773214-6aaec880-ee73-11e9-9d78-2604ab68a57b.jpg)

**Comment by lurch** [comment]
Sorry if I didn't understand your issue. I don't have a Mac myself, I was just pointing out that there are already "known problems" with macOS Catalina. Perhaps your error is indeed different.

**Comment by roura356a** [comment]
Exactly the same happening here. Once you give permissions to the app to be executed, you go to flash any image and... fails with above screenshot message.

**Comment by taiansu** [comment]
I can confirm that this issue is a duplicate of #2833, which just also provides the error message in DevTools. In the thread, there is a temporary solution by launching etcher using CLI.
```
sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
```

That solves the issue of the screenshot on this issue.

**Comment by SebiWolze** [comment]
> I can confirm that this issue is a duplicate of #2833, which just also provides the error message in DevTools. In the thread, there is a temporary solution by launching etcher using CLI.
> 
> ```
> sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> ```
> 
> That solves the issue of the screenshot on this issue, on my machine, at least.

That worked for me. 
Before I had the same issue like on the screenshots before.

**Comment by AegerBorder** [comment]
> That worked for me.
> Before I had the same issue like on the screenshots before.

Yep. Another confirmation here. Thanks for this workaround.

**Comment by majkassab** [comment]
> I can confirm that this issue is a duplicate of #2833, which just also provides the error message in DevTools. In the thread, there is a temporary solution by launching etcher using CLI.
> 
> ```
> sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> ```
> 
> That solves the error showing the screenshot on this issue, on my machine, at least.

That worked for me. thx

**Comment by thundron** [comment]
Closing as duplicate of #2833 , we have a PR open that will solve issues with macOS Catalina.
@stephendwolff Yes, we need to find the right entitlements for Etcher, as USB devices + a couple more don't seem to suffice for now

**Comment by AdvaitT17** [comment]
Worked for me as well! Thanks

**Comment by Aculisme** [comment]
Worked here too. Thanks!

**Comment by ygreq** [comment]
Can this bug be fixed, please? 
The terminal command worked for me as well, btw

**Comment by lurch** [comment]
@ygreq I don't have a Mac myself, but from what I've read elsewhere I thought this bug was fixed? :man_shrugging: 
What version of Etcher are you using?

**Comment by ygreq** [comment]
I was using 1.5.59.  I just updated to 1.5.76. And it works! Thank you for the heads up, lurch!!

**Comment by LanceHaverkamp** [comment]
As of March 2020, this is still not fixed in Linux. It asks for the root password, then fails.

**Comment by lurch** [comment]
@LanceHaverkamp I suggest you open a new issue and describe your problem in as much detail as possible.

**Comment by StefanoSGI** [comment]
+1 same issue reported in https://github.com/balena-io/etcher/issues/2933#issuecomment-541833707 still happening on Mac OS Catalina 10.15.4 with Etcher v.1.5.83 trying to flash `2020-02-13-raspbian-buster-lite.img`. 
- Pick image
- Select target
- Click `Flash!`
- Enter password to authorize app
- This appears:
<img width="800" alt="Screenshot 2020-05-03 at 4 17 22 PM" src="https://user-images.githubusercontent.com/25331099/80928488-9d5dd700-8d59-11ea-9f12-86ecac22eb4b.png">

**Comment by lurch** [comment]
@StefanoSGI Are you running on Catalina as a "non-admin" user? If so, does [this](https://github.com/balena-io/etcher/issues/3107#issuecomment-602047807) summarise what you're experiencing?

**Comment by StefanoSGI** [comment]
@lurch the account I'm using is an Admin on my laptop.

**Comment by stevyhacker** [comment]
@StefanoSGI still happening, the same scenario with ubuntu images and its derivatives images on Mac OS Catalina latest and admin user account.

**Comment by stevyhacker** [comment]
Just tasted the latest build 1.5.95 on Mac OS and it works fine now 😁

**Comment by ph00lt0** [comment]
Unfortunately I have the same issue. Just installed lastest version, nothing seems to help, neither starting it through terminal.

**Comment by davidmgrantham** [comment]
I having the same issue on build 1.5.101.
OS: MacOS Catalina 10.15.5

**Comment by tomaspiaggio** [comment]
I am also experiencing the issue. I am running a Macbook Pro 15 on Catalina (10.15.6). I have been flashing lots of images these last two weeks and I experienced this issue multiple times, with multiple different images (from the top of my memory fedora 32, Debian 10). These are the logs I am getting:

<img width="1680" alt="Screen Shot 2020-09-02 at 22 47 28" src="https://user-images.githubusercontent.com/18428646/92062225-95955a00-ed6e-11ea-98a4-3b92a43e99a5.png">
I did not get into reading the code, but this might help somebody.

**Comment by sscotth** [comment]
Same issue `Version 1.5.106`

**Comment by tazdrum73** [comment]
Catalina 10.15.6
BalenaEtcher 1.5.109

Same issue. Tried sudo and it did not work, but if I switch to root and start the app as root from cli it works.

**Comment by hahahaharada** [comment]
Yosemite OS

U need format flashdrive (FAT system) before flash distro. 
Otherwise it will give the same error... This is the trick! 

tested with and without sudo... 
sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher

**Comment by canehusker** [comment]
> > I can confirm that this issue is a duplicate of #2833, which just also provides the error message in DevTools. In the thread, there is a temporary solution by launching etcher using CLI.
> > ```
> > sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> > ```
> > 
> > 
> > That solves the issue of the screenshot on this issue, on my machine, at least.
> 
> That worked for me.
> Before I had the same issue like on the screenshots before.

Yes, that worked. Thank you. Running it from Mac (Catalina 10.15.6) kept failing.

**Comment by HelenGuohx** [comment]
I u**ncompressed the file in terminal to get the image**. And The problem solved. 
My OS version is  macOS mojave 10.14.6
Etcher version is Version 1.5.109 (1.5.109)

**Comment by SamuelMiller** [comment]
Hello, I intermittently get the same error even when running with sudo privileges through the terminal in Catalina--at least half the time or more. Sometimes, restarting my computer solves it, sometimes not.

**Comment by sebastianfelipe** [comment]
> I can confirm that this issue is a duplicate of #2833, which just also provides the error message in DevTools. In the thread, there is a temporary solution by launching etcher using CLI.
> 
> ```
> sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher
> ```
> 
> That solves the error showing the screenshot on this issue, on my machine, at least.

This man is a genius!

**Comment by PierreScerri** [comment]
I have done it as follows (on MacOS Catalina 10.15.3):

Launch Disk Utility
Format destination drive (FAT32 - GUID)
Unmount the drive.
Launch Balena Etcher normally.
Flash normally.

I have followed this sequence on 2 drives that were giving the error.

Hope it helps

**Comment by AlexanderJGomez** [comment]
> I have done it as follows (on MacOS Catalina 10.15.3):
> 
> Launch Disk Utility
> Format destination drive (FAT32 - GUID)
> Unmount the drive.
> Launch Balena Etcher normally.
> Flash normally.
> 
> I have followed this sequence on 2 drives that were giving the error.
> 
> Hope it helps

Tried running with `sudo` command but did not work. Unmounting the drive fixed it for me, thanks!

**Comment by almolinagithub** [comment]
The above worked for me too.

**Comment by maslaral** [comment]
The above worked for me. Except in addition to unmounting the drive, I had to launch Etcher via the command line with sudo.

**Comment by mhazley** [comment]
@AlexanderJGomez cheers - this worked!

**Comment by raindog308** [comment]
Have tried all fixes here - sudo, running as root, reformatting as GUID, yet the same issue (same error) persists.

This is Etcher 1.5.111 on macOS 10.15.6 Catalina.

**Comment by PierreScerri** [comment]
Did you unmount the drive before using Balena?

**Comment by raindog308** [comment]
If I unmount it, it does not show up in the Select Target.  If I mount it (just insert the card and it automounts), it shows up as "Apple SDXC Reader Media" on /dev/disk4.

**Comment by raindog308** [comment]
I see the issue...in Finder, you can only eject the volume (e.g., "UNTITLED") which also ejects the reader.  In Disk Utility, it's possible to eject the volume and still leave the reader mounted.  When I do that, it works.

**Comment by tszumowski** [comment]
@raindog308 I literally was just about the write the same thing haha. 
Hitting "Unmount" here did it for me. I didn't have to run as sudo either:

![image](https://user-images.githubusercontent.com/10282962/100804864-94220f00-33fb-11eb-9b4b-bbf22824c2e2.png)

**Comment by PierreScerri** [comment]
Yes, as I said previously, just unmount the drive in disk utility and use Balena to write the image.

**Comment by tszumowski** [comment]
> Yes, as I said previously, just unmount the drive in disk utility and use Balena to write the image.

Whoops! I missed your post in the mix of the others. Yes, your steps are perfect

**Comment by PierreScerri** [comment]
Thank you.

**Comment by WorldWideWebDev** [comment]
On your Mac, Go to  Firewall/ Privacy/ scroll down to Files and Folders, Ensure "Balena Etcher " Has access to "Removable Volumes" by ticking the box.

**Comment by PierreScerri** [comment]
@WorldWideWebDev Balena is not listed under Files and Folders on my Mac.  Cannot add it as the '+' is disabled even with the padlock unlocked.
